words:
  - asus
  - avenir
  - compat
  - consolas
  - fontsource
  - menlo
  - netdata
  - reekystive
  - xboard
  - zustand
flagWords:
  - blacklist -> blocklist
  - whitelist -> allowlist
suggestWords:
  - colour -> color
ignorePaths:
  - cspell.config.yaml
  - pnpm-lock.yaml
